# Generated by Django 6.0.3 on 2026-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
