# Generated by Django 6.0.3 on 2026-03-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0002_current_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current_user',
            options={},
        ),
        migrations.RemoveField(
            model_name='current_user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='current_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='current_user',
            name='last_name',
        ),
    ]
