# Generated by Django 6.0.3 on 2026-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0003_alter_current_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='current_user',
            name='otp_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
