# Generated by Django 6.0.3 on 2026-03-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0004_current_user_otp_current_user_otp_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='current_user',
            name='otp_expire',
        ),
    ]
