# Generated by Django 6.0.3 on 2026-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0005_remove_current_user_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
