# Generated by Django 6.0.3 on 2026-04-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0006_current_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_user',
            name='is_admin',
        ),
    ]
