# Generated by Django 6.0.3 on 2026-06-24 08:50

import HR_APP.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_APP', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='aadhar',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhaar',
            field=models.CharField(default='000000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Intern', 'Intern'), ('Contract', 'Contract'), ('Part Time', 'Part Time')], default='Full Time', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='NOT_AVAILABLE', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
        migrations.AddField(
            model_name='employeeextra',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeextra',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='HR_APP.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='official_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_document', models.FileField(blank=True, null=True, upload_to=HR_APP.models.employee_document_path)),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to=HR_APP.models.employee_document_path)),
                ('resume', models.FileField(blank=True, null=True, upload_to=HR_APP.models.employee_document_path)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to=HR_APP.models.employee_document_path)),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to=HR_APP.models.employee_document_path)),
                ('other_document', models.FileField(blank=True, null=True, upload_to=HR_APP.models.employee_document_path)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='HR_APP.employee')),
            ],
        ),
    ]
