# Generated by Django 6.0.3 on 2026-03-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='po_app.purchaseorder'),
        ),
    ]
