# Generated by Django 6.0.3 on 2026-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0002_alter_resource_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default='2026-04-03'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='po_excels/'),
        ),
    ]
