# Generated by Django 6.0.3 on 2026-07-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR_APP', '0004_remove_employee_location_remove_employee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('Leave', 'Leave'), ('Holiday', 'Holiday'), ('Weekend', 'Weekend'), ('Work From Home', 'Work From Home')], default='Present', max_length=30)),
                ('shift', models.CharField(choices=[('General', 'General'), ('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='General', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='HR_APP.employee')),
            ],
            options={
                'ordering': ['-attendance_date'],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
    ]
