# Generated by Django 6.0.3 on 2026-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
        ('HR_APP', '0004_remove_employee_location_remove_employee_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance'),
        ),
    ]
