# Generated by Django 6.0.3 on 2026-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_shift_alter_attendance_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.CharField(choices=[('General', 'General'), ('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='General', max_length=20),
        ),
    ]
