# Generated by Django 6.0.3 on 2026-07-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_alter_attendance_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
