# Generated by Django 6.0.3 on 2026-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0007_shift_alter_attendance_shift'),
        ('HR_APP', '0004_remove_employee_location_remove_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='early_departure_minutes',
            new_name='early_leave_minutes',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_early_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date'], name='Attendance__attenda_1b3337_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee'], name='Attendance__employe_ed1505_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='Attendance__status_a972c3_idx'),
        ),
    ]
